image: Ubuntu

build_script:
  - make
test_script:
  - ./bounds
  - ./demo
  - ./heap
  - ./test1
#  - lcov --directory . --capture --output-file coverage.info
#  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
#  - lcov --list coverage.info
#  - curl -Os https://uploader.codecov.io/latest/linux/codecov
#  - chmod +x codecov
#  - ./codecov -t ${CODECOV_TOKEN} -f coverage.info
