version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GIT
          command: 'apt-get update && apt-get install -y git'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install LCOV
          command: 'apt-get update && sudo apt-get install -y lcov'
      - run:
          name: Run make
          command: 'make'
      - run:
          name: Run test
          command: './test1'
      - run:
          name: Run gcov
          command: 'gcov test1.cpp'
      - run:
          name: Test lcov
          command: 'lcov --directory . --capture --output-file coverage.info'
      - run:
          name: Download codecov
          command: 'curl -Os https://uploader.codecov.io/latest/linux/codecov'
      - run:
          name: Run codecov
          command: 'chmod +x codecov && ./codecov -t ${CODECOV_TOKEN} -f coverage.info'
